/**
 * this will create a json file we can load into the Postman app.
 */

var PostmanCollection = require('../lib');
var fs = require('fs');


var postman = new PostmanCollection({
  name: 'test-collection',
  description: 'test collection generated by PostmanCollectionProgrammatically'
});

// add folders
postman.addFolder({name: 'folder-empty', description: 'an empty folder'});
postman.addFolder({name: 'folder', description: 'a folder'});
postman.addFolder({name: 'folder-methods', description: 'an other folder'});

// add requests
postman.addRequest({name: 'req-at-root', description: 'request item at the root', url: 'http://localhost:80'});
postman.addRequest({name: 'req-at-folder-1', url: 'http://localhost:80'}, 'folder');
postman.addRequest({name: 'req-into-new-folder', url: 'http://localhost:80'}, 'folder-new');
// methods...
postman.addRequest({name: 'req-method-get', url: 'http://localhost:80', method: 'get'}, 'folder-methods');
postman.addRequest({name: 'req-method-post', url: 'http://localhost:80', method: 'post'}, 'folder-methods');
postman.addRequest({name: 'req-method-put', url: 'http://localhost:80', method: 'put'}, 'folder-methods');
postman.addRequest({name: 'req-method-patch', url: 'http://localhost:80', method: 'patch'}, 'folder-methods');
postman.addRequest({name: 'req-method-delete', url: 'http://localhost:80', method: 'delete'}, 'folder-methods');
postman.addRequest({name: 'req-method-copy', url: 'http://localhost:80', method: 'copy'}, 'folder-methods');
postman.addRequest({name: 'req-method-head', url: 'http://localhost:80', method: 'head'}, 'folder-methods');
postman.addRequest({name: 'req-method-options', url: 'http://localhost:80', method: 'options'}, 'folder-methods');
postman.addRequest({name: 'req-method-link', url: 'http://localhost:80', method: 'link'}, 'folder-methods');
postman.addRequest({name: 'req-method-unlink', url: 'http://localhost:80', method: 'unlink'}, 'folder-methods');
postman.addRequest({name: 'req-method-purge', url: 'http://localhost:80', method: 'purge'}, 'folder-methods');
postman.addRequest({name: 'req-method-lock', url: 'http://localhost:80', method: 'lock'}, 'folder-methods');
postman.addRequest({name: 'req-method-unlock', url: 'http://localhost:80', method: 'unlock'}, 'folder-methods');
postman.addRequest({name: 'req-method-propfind', url: 'http://localhost:80', method: 'propfind'}, 'folder-methods');

fs.writeFile('test-postman-collection.json', postman.getJSON(), function(err) {
  if(err) console.error('Error:', e);
  else console.log('successfully written json file');
});
